set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_data[0]}]
set_property PACKAGE_PIN D1 [get_ports {AD_data[11]}]
set_property PACKAGE_PIN F2 [get_ports {AD_data[10]}]
set_property PACKAGE_PIN E2 [get_ports {AD_data[9]}]
set_property PACKAGE_PIN G4 [get_ports {AD_data[8]}]
set_property PACKAGE_PIN F4 [get_ports {AD_data[7]}]
set_property PACKAGE_PIN G2 [get_ports {AD_data[6]}]
set_property PACKAGE_PIN G1 [get_ports {AD_data[5]}]
set_property PACKAGE_PIN J4 [get_ports {AD_data[3]}]
set_property PACKAGE_PIN H4 [get_ports {AD_data[4]}]
set_property PACKAGE_PIN H2 [get_ports {AD_data[2]}]
set_property PACKAGE_PIN H1 [get_ports {AD_data[1]}]
set_property PACKAGE_PIN H9 [get_ports {AD_data[0]}]
set_property PACKAGE_PIN G9 [get_ports AD_clk]
set_property IOSTANDARD LVCMOS33 [get_ports AD_clk]




set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_data[0]}]
set_property PACKAGE_PIN W23 [get_ports {DA_data[13]}]
set_property PACKAGE_PIN V23 [get_ports {DA_data[12]}]
set_property PACKAGE_PIN Y23 [get_ports {DA_data[11]}]
set_property PACKAGE_PIN Y22 [get_ports {DA_data[10]}]
set_property PACKAGE_PIN AA25 [get_ports {DA_data[9]}]
set_property PACKAGE_PIN Y25 [get_ports {DA_data[8]}]
set_property PACKAGE_PIN Y21 [get_ports {DA_data[7]}]
set_property PACKAGE_PIN W21 [get_ports {DA_data[6]}]
set_property PACKAGE_PIN AC24 [get_ports {DA_data[5]}]
set_property PACKAGE_PIN AB24 [get_ports {DA_data[4]}]
set_property PACKAGE_PIN Y26 [get_ports {DA_data[3]}]
set_property PACKAGE_PIN W25 [get_ports {DA_data[2]}]
set_property PACKAGE_PIN AC26 [get_ports {DA_data[1]}]
set_property PACKAGE_PIN AB26 [get_ports {DA_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DA_clk]
set_property PACKAGE_PIN U21 [get_ports DA_clk]



# 矩阵键盘
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property PACKAGE_PIN D26 [get_ports {col[3]}]
set_property PACKAGE_PIN D25 [get_ports {col[2]}]
set_property PACKAGE_PIN G26 [get_ports {col[1]}]
set_property PACKAGE_PIN E23 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property PACKAGE_PIN E26 [get_ports {row[3]}]
set_property PACKAGE_PIN E25 [get_ports {row[2]}]
set_property PACKAGE_PIN H26 [get_ports {row[1]}]
set_property PACKAGE_PIN F23 [get_ports {row[0]}]

#底板上的LED
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN L22 [get_ports {led[3]}]
set_property PACKAGE_PIN L23 [get_ports {led[2]}]
set_property PACKAGE_PIN N26 [get_ports {led[1]}]
set_property PACKAGE_PIN K22 [get_ports {led[0]}]
# 核心板上的LED
set_property IOSTANDARD LVCMOS33 [get_ports core_led]
set_property PACKAGE_PIN J19 [get_ports core_led]
# 合成的数字模拟方波
set_property IOSTANDARD LVCMOS33 [get_ports conbined_wave]
set_property PACKAGE_PIN P23 [get_ports conbined_wave]
# 数码管
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property PACKAGE_PIN G21 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports rclk]
set_property PACKAGE_PIN J26 [get_ports rclk]
set_property IOSTANDARD LVCMOS33 [get_ports DIO]
set_property PACKAGE_PIN F22 [get_ports DIO]
# 地板上的按键
set_property IOSTANDARD LVCMOS33 [get_ports {key_input[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_input[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_input[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_input[0]}]
set_property PACKAGE_PIN V21 [get_ports {key_input[4]}]
set_property PACKAGE_PIN T24 [get_ports {key_input[3]}]
set_property PACKAGE_PIN T25 [get_ports {key_input[2]}]
set_property PACKAGE_PIN R25 [get_ports {key_input[1]}]
set_property PACKAGE_PIN P25 [get_ports {key_input[0]}]





set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN U22 [get_ports sys_clk]
set_property PACKAGE_PIN H19 [get_ports rst_n]


create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} [get_ports sys_clk]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]

set_property PULLUP true [get_ports {col[3]}]
set_property PULLUP true [get_ports {col[2]}]
set_property PULLUP true [get_ports {col[1]}]
set_property PULLUP true [get_ports {col[0]}]
